services:
    redis:
        image: redis:7.0-alpine
        container_name: redis2
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./volumes/redis/:/etc/redis/
        ports:
            - 6379:6379
        networks:
            - mks
        restart: unless-stopped

    backend:
        image: mosesmbadi/easymedbackend
        container_name: backend
        #command: uvicorn --host 0.0.0.0 --port 8080 easymed.asgi:application
        ports:
            - 8080:8080
        env_file:
            - ./.env
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - mks

    worker:
        image: mosesmbadi/easymedbackend
        container_name: worker
        command: celery -A easymed worker --loglevel=INFO        
        restart: unless-stopped
        env_file:
            - ./.env    
        depends_on:
            - backend
            - redis
        networks:
            - mks   

    frontend:
        image: mosesmbadi/easymedfrontend
        container_name: front-end
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - mks    

networks:
    mks:
        name: mks
        driver: bridge
