services:
    postgres:
    # Will be moved to bare-metal install in prod
        image: postgres:15
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
        ports:
        - "5433:5432"
        volumes:
        - pg_data:/var/lib/postgresql/data
        networks:
        - mks
    redis:
        image: redis:7.0-alpine
        container_name: redis2
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - ./volumes/redis/:/etc/redis/
        ports:
            - 6379:6379
        networks:
            - mks
        restart: unless-stopped

    backend:
        image: mosesmbadi/easymedbackend
        container_name: backend
        command: uvicorn --host 0.0.0.0 --port 8080 easymed.asgi:application
        ports:
            - 8080:8080
        env_file:
            - ./.env
        restart: unless-stopped
        depends_on:
            - redis
        networks:
            - mks

    worker:
        image: mosesmbadi/easymedbackend
        container_name: worker
        command: celery -A easymed worker --loglevel=INFO        
        restart: unless-stopped
        env_file:
            - ./.env    
        depends_on:
            - backend
            - redis
        networks:
            - mks   

    frontend:
        image: mosesmbadi/easymedfrontend
        container_name: front-end
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - mks    

volumes:
    pg_data:
    
networks:
    mks:
        name: mks
        driver: bridge
