# Generated by Django 5.0.10 on 2025-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
