# Generated by Django 5.0.6 on 2024-07-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_insurancecompany'),
        ('patient', '0010_alter_patient_insurances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
    ]
