# Generated by Django 5.0.10 on 2025-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_cash_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cash_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
