# Generated by Django 5.0.10 on 2025-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_cash_paid_alter_invoice_total_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
