# Generated by Django 5.0.6 on 2024-07-31 01:01

from django.db import migrations

'''
    creates cash pay mode on migration
'''

def create_cash_pay_mode(apps, schema_editor):
    PaymentMode = apps.get_model("billing", "PaymentMode")
    PaymentMode.objects.create(
        payment_category='cash',
        paymet_mode='cash' 
    )

    


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_delete_insurancecompany'),
    ]

    operations = [
        migrations.RunPython(create_cash_pay_mode)
    ]
