# Generated by Django 5.0.10 on 2025-02-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_invoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(null=True)),
                ('payment_created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmode')),
            ],
        ),
    ]
