# Generated by Django 5.0.6 on 2024-07-31 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20240731_0401'),
        ('company', '0003_auto_20240731_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.insurancecompany'),
        ),
    ]
