# Generated by Django 5.0.6 on 2024-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentmode_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed')], default='pending', max_length=10),
        ),
    ]
