# Generated by Django 5.0.10 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slow_moving_period',
            field=models.IntegerField(default=90),
        ),
    ]
