# Generated by Django 5.0.10 on 2025-03-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceitemsaleprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slow_moving_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantity_at_hand', models.PositiveIntegerField()),
                ('lot_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('main_inventory', models.ForeignKey(help_text='Main inventory record this was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
