# Generated by Django 5.0.6 on 2024-07-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_insurancecompany'),
        ('inventory', '0002_alter_incomingitem_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInsuranceSaleprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.insurancecompany')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
