# Generated by Django 5.0.6 on 2024-07-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_insurancecompany'),
        ('inventory', '0003_inventoryinsurancesaleprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryinsurancesaleprice',
            unique_together={('inventory_item', 'insurance_company')},
        ),
    ]
