# Generated by Django 5.0.10 on 2026-04-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_incomingitem_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SurgicalEquipment', 'Surgical Equipment'), ('LabReagent', 'Lab Reagent'), ('LabConsumable', 'Lab Consumable'), ('Drug', 'Drug'), ('Furniture', 'Furniture'), ('Lab Test', 'Lab Test'), ('General Appointment', 'General Appointment'), ('Specialized Appointment', 'Specialized Appointment'), ('general', 'General')], max_length=255),
        ),
    ]
