# Generated by Django 5.0.10 on 2026-09-06 08:55

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    '''
    Existing requisitions already carry the facts the status is derived from,
    so read it off them rather than leaving every historical row as Pending.
    '''
    Requisition = apps.get_model('inventory', 'Requisition')
    for requisition in Requisition.objects.prefetch_related('items').iterator(chunk_size=500):
        if not requisition.department_approved:
            status = 'PENDING'
        elif not requisition.procurement_approved:
            status = 'DEPARTMENT_APPROVED'
        else:
            approved = [line for line in requisition.items.all() if line.quantity_approved > 0]
            ordered = sum(1 for line in approved if line.ordered)
            if not approved or ordered == 0:
                status = 'PROCUREMENT_APPROVED'
            elif ordered == len(approved):
                status = 'ORDERED'
            else:
                status = 'PARTIALLY_ORDERED'
        Requisition.objects.filter(pk=requisition.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_requisition_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DEPARTMENT_APPROVED', 'Department approved'), ('PROCUREMENT_APPROVED', 'Procurement approved'), ('PARTIALLY_ORDERED', 'Partially ordered'), ('ORDERED', 'Ordered')], default='PENDING', help_text='Where the requisition has reached. Derived from the approval flags and how many of its lines have been ordered -- never set directly, so it cannot drift from them.', max_length=30),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
