# Generated by Django 5.0.10 on 2026-09-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_requisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='closed_as',
            field=models.CharField(blank=True, choices=[('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], help_text='Set when the requisition is rejected or cancelled; blank while it is live', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_closed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='closed_reason',
            field=models.CharField(blank=True, default='', help_text='Why it was rejected or cancelled', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DEPARTMENT_APPROVED', 'Department approved'), ('PROCUREMENT_APPROVED', 'Procurement approved'), ('PARTIALLY_ORDERED', 'Partially ordered'), ('ORDERED', 'Ordered'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Where the requisition has reached. Derived from the approval flags, how many of its lines have been ordered, and whether it was closed -- never set directly, so it cannot drift from them.', max_length=30),
        ),
    ]
