# Generated by Django 5.0.10 on 2026-09-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_requisition_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Departmental head. May receive stock inwards for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category_one',
            field=models.CharField(choices=[('Resale', 'Resale'), ('Internal', 'Internal (Consumable)')], default='Resale', help_text='Whether the item is bought for resale or for internal consumption', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantity_per_use', models.PositiveIntegerField(default=1, help_text='Base units of the consumable used per ONE base unit of the parent item')),
                ('is_required', models.BooleanField(default=True, help_text='Required accompaniments block billing when out of stock; optional ones only warn')),
                ('consumable', models.ForeignKey(help_text='The accompaniment used up alongside it', limit_choices_to={'category_one': 'Internal'}, on_delete=django.db.models.deletion.PROTECT, related_name='consumed_by_links', to='inventory.item')),
                ('item', models.ForeignKey(help_text='The sellable or billable item', on_delete=django.db.models.deletion.CASCADE, related_name='consumable_links', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Item Consumable',
                'verbose_name_plural': 'Item Consumables',
                'ordering': ['item', 'consumable'],
                'unique_together': {('item', 'consumable')},
            },
        ),
    ]
