# Generated by Django 4.2.5 on 2023-11-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authperms', '0001_initial'),
        ('customuser', '0002_remove_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_users', to='authperms.group'),
        ),
    ]
