# Generated by Django 5.0.10 on 2026-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customuser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Granted individually. Lets this user receive stock inwards and adjust balances without being a sysadmin or a departmental head.'),
        ),
    ]
