# Generated by Django 4.2.5 on 2023-10-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('order_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderbill')),
                ('patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('test_profile_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('test_element', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('lab_test_request_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_profile_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(max_length=255)),
                ('molecular_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
