# Generated by Django 5.0.3 on 2024-06-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patient', '0002_remove_attendanceprocess_qualitativelabtest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestresultqualitative',
            name='lab_test_request',
        ),
        migrations.RemoveField(
            model_name='labtestresultqualitative',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='qualitativeresultsverification',
            name='lab_results',
        ),
        migrations.RemoveField(
            model_name='qualitativeresultsverification',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='qualitativeresultsverification',
            name='lab_test_request',
        ),
        migrations.RemoveField(
            model_name='labtestprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labtestresult',
            name='category',
        ),
        migrations.AddField(
            model_name='labtestpanel',
            name='is_qualitative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestpanel',
            name='is_quantitative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='category',
            field=models.CharField(default='quantitative', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='result',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientsample',
            name='has_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientsample',
            name='test_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestrequest'),
        ),
        migrations.DeleteModel(
            name='LabTestResultPanelQualitative',
        ),
        migrations.DeleteModel(
            name='LabTestResultQualitative',
        ),
        migrations.DeleteModel(
            name='QualitativeResultsVerification',
        ),
    ]
