# Generated by Django 4.2.5 on 2023-10-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='test_profile_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile'),
        ),
        migrations.AddField(
            model_name='labtestprofile',
            name='item_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='labtestpanel',
            name='test_profile_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile'),
        ),
        migrations.AddField(
            model_name='labreagent',
            name='item_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
