# Generated by Django 4.2.5 on 2023-09-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientidentifier',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.patientidentifier'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.patientidentifier'),
        ),
        migrations.AddField(
            model_name='labreagent',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sale'),
        ),
    ]
