# Generated by Django 5.0.10 on 2025-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labtestkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestkit',
            name='number_of_tests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
