# Generated by Django 5.0.10 on 2025-02-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtestkit_number_of_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestKitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('lab_test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestkit')),
            ],
        ),
    ]
