# Generated by Django 5.0.10 on 2025-02-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_labtestrequest_note'),
        ('laboratory', '0004_labtestkitcounter'),
    ]

    operations = [
    ]
