# Generated by Django 5.0.3 on 2024-06-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_remove_labtestrequest_has_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestrequestpanel',
            old_name='sample_code',
            new_name='test_code',
        ),
        migrations.RenameField(
            model_name='patientsample',
            old_name='sample_collected',
            new_name='is_sample_collected',
        ),
        migrations.RenameField(
            model_name='patientsample',
            old_name='test_req',
            new_name='lab_test_request',
        ),
        migrations.RemoveField(
            model_name='labtestrequestpanel',
            name='is_sample_collected',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='has_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='category',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='patient_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.patientsample'),
        ),
        migrations.AddField(
            model_name='patientsample',
            name='patient_sample_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsample',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.processtestrequest'),
        ),
        migrations.AlterField(
            model_name='labtestpanel',
            name='is_quantitative',
            field=models.BooleanField(default=True),
        ),
    ]
