# Generated by Django 5.0.3 on 2024-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_rename_sample_code_labtestrequestpanel_test_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequestpanel',
            name='category',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='labtestrequestpanel',
            name='test_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
