# Generated by Django 5.0.6 on 2024-06-20 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_labtestrequestpanel_result_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
