# Generated by Django 5.0.10 on 2026-04-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_lab_consumable_and_specimen_consumable'),
        ('laboratory', '0021_lab_reagent_inventory_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_collection', models.PositiveIntegerField(default=1, help_text='Units of this consumable deducted each time a sample is collected')),
                ('item', models.ForeignKey(limit_choices_to={'category': 'LabConsumable'}, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_consumable_links', to='inventory.item')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='laboratory.specimen')),
            ],
            options={
                'verbose_name': 'Specimen Consumable',
                'verbose_name_plural': 'Specimen Consumables',
                'unique_together': {('specimen', 'item')},
            },
        ),
    ]
