# Generated by Django 5.0.10 on 2026-09-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_specimen_consumables_to_item_consumables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecimenConsumable',
        ),
    ]
