# Generated by Django 4.2.5 on 2023-09-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customusers', '0002_customuser_role'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_no', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('residence', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.insurancecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.CharField(max_length=45)),
                ('start_date', models.CharField(max_length=45)),
                ('created_by', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed')], default='pending', max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=45)),
                ('frequency', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('notes', models.TextField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('relationship', models.CharField(max_length=40)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.contactdetails')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_date', models.DateTimeField()),
                ('idappointment', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('doctor_id', models.CharField(max_length=45)),
                ('appointment_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reason', models.CharField(max_length=45)),
                ('date_created', models.CharField(max_length=45)),
                ('date_changed', models.CharField(max_length=45)),
                ('changed_by', models.CharField(max_length=45)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customusers.customuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
