# Generated by Django 4.2.5 on 2023-09-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
