# Generated by Django 5.0.3 on 2024-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprocess',
            name='qualitativeLabTest',
        ),
        migrations.AddField(
            model_name='attendanceprocess',
            name='patient_number',
            field=models.CharField(default=999, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='unique_id',
            field=models.CharField(default=1, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
