# Generated by Django 5.0.10 on 2025-02-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_nextofkin_contacts_alter_nextofkin_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='residence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='tel_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
