# Generated by Django 5.0.3 on 2024-06-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_labresult_attendanceprocess_lab_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceprocess',
            old_name='process_test_re',
            new_name='process_test_req',
        ),
    ]
