# Generated by Django 5.0.6 on 2024-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_process_test_re_attendanceprocess_process_test_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribeddrug',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescribeddrug',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
