# Generated by Django 5.0.6 on 2024-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_prescribeddrug_is_dispensed_prescribeddrug_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
    ]
