# Generated by Django 5.0.6 on 2024-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_attendanceprocess_lab_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='patient.insurancecompany'),
        ),
    ]
