# Generated by Django 5.0.6 on 2024-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_insurancecompany'),
        ('patient', '0009_delete_insurancecompany_alter_patient_insurances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='company.insurancecompany'),
        ),
    ]
