# Generated by Django 5.0.6 on 2024-07-31 01:10

from django.db import migrations

'''
    creates permissions on migration
'''

def create_app_permissions(apps, schema_editor):
    Permission = apps.get_model("authperms", "Permission")
    permissions = [
        'CAN_ACCESS_DOCTOR_DASHBOARD',
        'CAN_ACCESS_GENERAL_DASHBOARD',
        'CAN_ACCESS_ADMIN_DASHBOARD',
        'CAN_ACCESS_RECEPTION_DASHBOARD',
        'CAN_ACCESS_NURSING_DASHBOARD',
        'CAN_ACCESS_LABORATORY_DASHBOARD',
        'CAN_ACCESS_PATIENTS_DASHBOARD',
        'CAN_ACCESS_AI_ASSISTANT_DASHBOARD',
        'CAN_ACCESS_ANNOUNCEMENT_DASHBOARD',
        'CAN_ACCESS_PHARMACY_DASHBOARD',
        'CAN_ACCESS_INVENTORY_DASHBOARD',
        'CAN_ACCESS_BILLING_DASHBOARD',
    ]
    for perm_name in permissions:
        Permission.objects.create(name=perm_name)

'''
    creates groups on migration
'''

def create_app_groups(apps, schema_editor):
    Group = apps.get_model("authperms", "Group")
    sys_admin = Group.objects.create(name='SYS_ADMIN')
    Group.objects.create(name='PATIENT')
    Group.objects.create(name='DOCTOR')
    Group.objects.create(name='PHARMACIST')
    Group.objects.create(name='RECEPTIONIST')
    Group.objects.create(name='LAB_TECH')
    Group.objects.create(name='NURSE')

    '''
    adds all permissions to sysadmin
    '''
    Permission = apps.get_model("authperms", "Permission")
    permissions = Permission.objects.all()
    sys_admin.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('authperms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_app_permissions),
        migrations.RunPython(create_app_groups),
    ]
