name: Destroy Infrastructure

on:
  workflow_dispatch: # Trigger manually

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./deployment

      - name: Plan Terraform Destroy
        run: terraform plan -destroy -out=tfplan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Destroy Terraform Infrastructure
        run: terraform destroy -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Cleanup Local Files
        run: |
          rm -f ./deployment/inventory.ini
          echo "Terraform destroy completed and local files cleaned."
