name: Build, Test, and Push to Registry

on:
  push:
    branches: [ dev-moses ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ./backend
          pip install -r requirements.txt
          pip install pytest
          pytest .

      # - name: Run tests
      #   run: |
      #     cp .env.sample .env
      #     cd ./backend
      #     pytest .

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print Docker Username
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build and push backend image
        run: |
          cd ./backend
          docker build . -t mosesmbadi/easymedbackend:latest
          docker push mosesmbadi/easymedbackend:latest

      - name: Build and push frontend image
        run: |
          cd ./front-end
          docker build . -t mosesmbadi/easymedfrontend:latest
          docker push mosesmbadi/easymedfrontend:latest

# ==================== Deployment ============================
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: deployment

      - name: Apply Terraform changes
        run: terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Save Terraform output
        id: get_ip
        run: echo "SERVER_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
        working-directory: deployment

  ansible:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Run Ansible Playbook
        run: |
          echo "[app_server]" > inventory.ini
          ansible-playbook -i deployment/inventory.ini ansible-playbook.yml
        working-directory: deployment     